name: Pre-commit Manually

on:
  pull_request:
  push:

jobs:
  pre-commit-manual:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: true # hopefully keep the .git folder

      - name: Install dependencies
        run: |
          apk update
          apk add git npm py3-virtualenv yamlfmt
          npm install prettier @taplo/cli
          uv tool install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
